// SwarmPortal.FrontEnd/src/app/navigation/navigation.component.ts
import { Component, OnInit } from '@angular/core';
import { OAuthService } from 'angular-oauth2-oidc';
import { HttpService } from '../services/http.service';
import { IdentityClaims } from '../services/IdentityClaims';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.scss']
})
export class NavigationComponent implements OnInit {

  constructor(private http: HttpService,
    private oauth: OAuthService) { }

  get Identity(): IdentityClaims | null {
    return this.http.Identity;
  }
  get Roles(): string[] {
    return this.http.Identity?.roles || [];
  }
  get isLoggedIn(): boolean {
    return this.http.Identity != null;
  }
  ngOnInit(): void {
  }
  login() {
    this.oauth.initCodeFlow();

  }
  logout() {
    this.oauth.logOut();
  }

}

<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid justify-content-start">
    <a class="navbar-brand" routerLink="/">SwarmPortal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link" routerLink="/">Home</a>
        </li>
        <li class="nav-item dropdown" *ngIf="isLoggedIn && Roles.includes('admin')">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Admin
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" routerLink="admin/links" >Manage Links</a></li>
            <li><a class="dropdown-item" routerLink="admin/groups" >Manage Link Groups</a></li>
            <li><a class="dropdown-item" routerLink="admin/roles" >Manage Roles</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <form class="container-fluid justify-content-end">
    <button *ngIf="isLoggedIn" class="btn disabled btn-sm btn-outline-secondary me-2" type="button">Welcome {{Identity?.given_name}}</button>
    <button *ngIf="isLoggedIn" class="btn btn-outline-success me-2" type="button" (click)="logout()">Logout</button>
    <button *ngIf="!isLoggedIn" class="btn btn-outline-success me-2" type="button" (click)="login()">Login</button>
  </form>
</nav>

// SwarmPortal.React/src/Navigation.tsx
import React from 'react';
import { ApiClient } from './services/apiClient';

class Navigation extends React.Component<{client: ApiClient}, { }> {
    client: ApiClient;
    constructor(props: {client: ApiClient}) {
        super(props);
        this.client = props.client;
    }

    async logIn() {
        await this.client.login();
    }
    async logOut() {
        await this.client.logOut();
    }
    render(): React.ReactNode {
        return (
        <nav className="navbar navbar-expand-md navbar-light bg-light">
            <div className="container-fluid justify-content-start">
                <a className="navbar-brand" href="/">SwarmPortal</a>
                <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="navbarSupportedContent">
                <ul className="navbar-nav me-auto mb-2 mb-md-0">
                    <li className="nav-item">
                    <a className="nav-link" href="/">Home</a>
                    </li>
                    
                    {/* {this.client.isLoggedIn && this.client.
                    <li class="nav-item dropdown" *ngIf="isLoggedIn && Roles.includes('admin')">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Admin
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" routerLink="admin/links" >Manage Links</a></li>
                        <li><a class="dropdown-item" routerLink="admin/groups" >Manage Link Groups</a></li>
                        <li><a class="dropdown-item" routerLink="admin/roles" >Manage Roles</a></li>
                    </ul>
                    </li> */}
                </ul>
                </div>
            </div>
            <form className="container-fluid justify-content-end">
                {this.client.isLoggedIn && <button className="btn btn-sm me-2" type="button">Welcome {this.client.token.given_name}</button>}
                {this.client.isLoggedIn && <button className="btn btn-outline-success me-2" type="button" onClick={() => this.logOut()}>Logout</button>}
                {!this.client.isLoggedIn && <button className="btn btn-outline-success me-2" type="button" onClick={() => this.logIn()} >Login</button>} 
                
            </form>
        </nav>
        );


    }    
}

export default Navigation;
